# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-01 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='catrgory',
            field=models.CharField(choices=[('jyjg', '\u6559\u80b2\u673a\u6784'), ('gr', '\u4e2a\u4eba'), ('shzz', '\u793e\u4f1a\u7ec4\u7ec7')], default='gr', max_length=20, verbose_name='\u673a\u6784\u7c7b\u522b'),
        ),
    ]
