# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-03 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=300, verbose_name='\u89c6\u9891\u5730\u5740'),
        ),
    ]
