# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-03 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_teacher_tell'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='my_url',
            field=models.FileField(blank=True, null=True, upload_to='courses/%Y/%m', verbose_name='\u89c6\u9891\u6587\u4ef6'),
        ),
    ]
