# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180504_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverfiyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '\u6ce8\u518c'), ('forget', '\u5fd8\u8bb0\u5bc6\u7801')], max_length=30, verbose_name='\u9a8c\u8bc1\u7801\u7c7b\u578b'),
        ),
    ]
